version: "3"
services:

  redis: 
    image: redislabs/redisgraph 
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data/redisinsight:/db
    depends_on:
      - redis

  #redis:
  #  image: redis/redis-stack
  #  ports:
  #    - "6379:6379"
  #    - "8001:8001"
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - ./data/redis:/data

